version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.6
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2.4.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_HEAP_OPTS=-Xmx192m -Xms192m
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  postgres:
    image: eventuateio/eventuate-postgres:0.9.0.RC2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate
    volumes:
      - happyride-trip-pgdata:/var/lib/postgresql/data
#      - ./my-postgres.conf:/etc/postgresql.conf
#      - ./initialize-postgres.sql:/docker-entrypoint-initdb.d/1-initialize-postgres.sql
#    command:
#      - "postgres"
#      - "-c"
#      - "config_file=/etc/postgresql.conf"
  cdc-service:
    image: eventuateio/eventuate-cdc-service:0.6.0.RC3
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/eventuate
      SPRING_DATASOURCE_USERNAME: eventuate
      SPRING_DATASOURCE_PASSWORD: eventuate
      SPRING_DATASOURCE_TEST_ON_BORROW: "true"
      SPRING_DATASOURCE_VALIDATION_QUERY: SELECT 1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_READER_NAME: PostgresWalReader
      EVENTUATE_CDC_READER_POSTGRESWALREADER_TYPE: postgres-wal
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEURL: jdbc:postgresql://postgres/eventuate
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEUSERNAME: eventuate
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEPASSWORD: eventuate
      EVENTUATE_CDC_READER_POSTGRESWALREADER_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_POSTGRESWALREADER_LEADERSHIPLOCKPATH: /eventuatelocal/cdc/leader/pipeline/1

      EVENTUATE_CDC_PIPELINE_1_TYPE: eventuate-local
      EVENTUATE_CDC_PIPELINE_1_READER: POSTGRESWALREADER
volumes:
  happyride-trip-pgdata: