version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: happyride-driver-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - happyride-driver-pgdata:/var/lib/postgresql/data
volumes:
  happyride-driver-pgdata: